name: Integration Tests

on:
  push:
    branches: 
      - 'feat/GEON-1496-Oppsett-av-testmiljø'
      - main
  pull_request:
    branches: 
      - 'feat/GEON-1496-Oppsett-av-testmiljø'
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: asd
      DB_USER: asd
      DB_PASSWORD: asd
      AZURE_GPT_API_KEY: ${{ secrets.AZURE_GPT_API_KEY }}
      AZURE_GPT_ENDPOINT: ${{ secrets.AZURE_GPT_ENDPOINT }}
      AZURE_EMBEDDING_API_KEY: ${{ secrets.AZURE_EMBEDDING_API_KEY }}
      AZURE_EMBEDDING_ENDPOINT: ${{ secrets.AZURE_EMBEDDING_ENDPOINT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create .env file
      run: |
        echo "DB_HOST=database" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_NAME=asd" >> .env
        echo "DB_USER=asd" >> .env
        echo "DB_PASSWORD=asd" >> .env
        echo "AZURE_GPT_API_KEY=${{ secrets.AZURE_GPT_API_KEY }}" >> .env
        echo "AZURE_GPT_ENDPOINT=${{ secrets.AZURE_GPT_ENDPOINT }}" >> .env
        echo "AZURE_EMBEDDING_API_KEY=${{ secrets.AZURE_EMBEDDING_API_KEY }}" >> .env
        echo "AZURE_EMBEDDING_ENDPOINT=${{ secrets.AZURE_EMBEDDING_ENDPOINT }}" >> .env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests psycopg2-binary

    - name: Build and start services
      run: |
        docker-compose up -d
        sleep 30  # Wait for services to be ready

    - name: Run integration tests
      run: |
        # Add your test commands here
        python -m pytest tests/test_services.py -v

    - name: Show logs on failure
      if: failure()
      run: docker-compose logs

    - name: Clean up
      if: always()
      run: docker-compose down