name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer avhengigheter
        run: |
          pip install -r requirements.txt

      - name: Kjør tester
        run: |
          pytest
