name: Backend Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut hovedgrenen (main)
        uses: actions/checkout@v4
        with:
          ref: main  # Sikrer at vi bruker filer fra main

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "⚠️ Ingen requirements.txt funnet i main"; fi

      - name: Kjør tester med pytest
        run: pytest --disable-warnings || echo "⚠️ Testene feilet, men fortsetter workflow"
