name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Kjør tester med pytest
        env:
          TEST_DATABASE_URL: sqlite:///test.db  # Midlertidig SQLite-database
        run: pytest --disable-warnings